### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by apurvaojas** [i18n-components/i18n-components#1]
## Why contribute to i18n-components docs?
i18n-components is built with brilliance and so you may want to know how:
your dev hot reload server builds and rebuilds in matters of seconds and milliseconds
the client site will be an SPA, code-split by route, and pages are load lightning fast without even a spinner, how is that even possible 🌚
site works even without javascript
Your very chance of experiencing docs composed from scratch, rephrase, from code, to human language on a popular OS project
Enjoy the pleasure of finding things out, teach and share it with others, practice writing skills

#### Docs

- [ ] Introduction
- [x] Contribution Guide lines
- [ ] Usage Examples (Input Number)
- [ ] Logo
- [x] License
- [x] Issue Templates and PR template
